export type AerodashComponentCategory =
  | "foundation"
  | "primitive"
  | "overlay"
  | "form"
  | "data"
  | "feedback"
  | "navigation"
  | "shell"
  | "utility"

export type AerodashComponentKind =
  | "token"
  | "primitive"
  | "compound"
  | "composite"
  | "state"
  | "utility"

export interface AerodashComponentEntry {
  id: string
  name: string
  category: AerodashComponentCategory
  kind: AerodashComponentKind
  source: string
  css: readonly string[]
  exports: readonly string[]
  description: string
}

export const aerodashComponents = [
  {
    id: "tokens",
    name: "Tokens",
    category: "foundation",
    kind: "token",
    source: "tokens.ts",
    css: [],
    exports: ["fonts", "fontSize", "lineHeight", "fontWeight", "letterSpacing", "radii", "colors", "motion"],
    description: "Runtime TypeScript tokens for typography, color, radius, and motion.",
  },
  {
    id: "button",
    name: "Button",
    category: "primitive",
    kind: "compound",
    source: "button.tsx",
    css: ["aerodash.css", "button.css"],
    exports: ["Button", "ButtonRoot", "ButtonUnderlay", "ButtonInner", "ButtonCap", "ButtonLabel", "ButtonWell"],
    description: "Primary action chrome with shorthand and named compound parts.",
  },
  {
    id: "section-header",
    name: "SectionHeader",
    category: "primitive",
    kind: "compound",
    source: "section-header.tsx",
    css: [],
    exports: ["SectionHeader", "SectionHeaderRoot", "SectionHeaderChrome", "SectionHeaderIcon", "SectionHeaderLabel", "SectionHeaderEnd"],
    description: "Labeled section chrome with active, dark, and dotted treatments.",
  },
  {
    id: "input",
    name: "Input",
    category: "form",
    kind: "compound",
    source: "input.tsx",
    css: ["aerodash.css", "input.css"],
    exports: ["Input", "InputRoot", "InputControl", "InputAddon"],
    description: "Chrome text input with leading/trailing addons and invalid state.",
  },
  {
    id: "chip",
    name: "Chip",
    category: "primitive",
    kind: "compound",
    source: "chip.tsx",
    css: ["aerodash.css", "chip.css"],
    exports: ["Chip", "ChipRoot", "ChipLabel", "ChipDismiss"],
    description: "Compact uppercase tag for filters, labels, and statuses.",
  },
  {
    id: "segmented",
    name: "SegmentedControl",
    category: "form",
    kind: "compound",
    source: "segmented.tsx",
    css: ["aerodash.css", "segmented.css"],
    exports: ["SegmentedRoot", "SegmentedItem"],
    description: "Single-select pill or slanted segmented control.",
  },
  {
    id: "card",
    name: "Card",
    category: "primitive",
    kind: "compound",
    source: "card.tsx",
    css: ["card.css"],
    exports: ["Card", "CardRoot", "CardHeader", "CardHeaderId", "CardHeaderTitle", "CardHeaderStatus", "CardBody", "CardValue", "CardMeta", "CardFooter"],
    description: "Y2K container surface with header cap, body well, and footer.",
  },
  {
    id: "dialog",
    name: "Dialog",
    category: "overlay",
    kind: "compound",
    source: "dialog.tsx",
    css: ["aerodash.css", "dialog.css"],
    exports: ["DialogRoot", "DialogTrigger", "DialogPortal", "DialogBackdrop", "DialogContent", "DialogHeader", "DialogTitle", "DialogDescription", "DialogBody", "DialogFooter", "DialogClose"],
    description: "Radix-backed modal with AeroDash backdrop, chrome, and focus behavior.",
  },
  {
    id: "switch",
    name: "Switch",
    category: "form",
    kind: "primitive",
    source: "switch.tsx",
    css: ["aerodash.css", "switch.css"],
    exports: ["Switch"],
    description: "Radix-backed binary toggle with shared AeroDash focus and press states.",
  },
  {
    id: "checkbox",
    name: "Checkbox",
    category: "form",
    kind: "primitive",
    source: "checkbox.tsx",
    css: ["aerodash.css", "checkbox.css"],
    exports: ["Checkbox"],
    description: "Radix-backed checkbox with checked and indeterminate glyphs.",
  },
  {
    id: "radio-group",
    name: "RadioGroup",
    category: "form",
    kind: "compound",
    source: "radio-group.tsx",
    css: ["aerodash.css", "radio-group.css"],
    exports: ["RadioGroupRoot", "RadioBare", "RadioItem"],
    description: "Radix-backed radio group plus labeled item convenience component.",
  },
  {
    id: "tooltip",
    name: "Tooltip",
    category: "overlay",
    kind: "compound",
    source: "tooltip.tsx",
    css: ["tooltip.css"],
    exports: ["Tooltip", "TooltipProvider", "TooltipRoot", "TooltipTrigger", "TooltipPortal", "TooltipContent"],
    description: "Radix-backed tooltip primitives and shorthand wrapper.",
  },
  {
    id: "avatar",
    name: "Avatar",
    category: "primitive",
    kind: "primitive",
    source: "avatar.tsx",
    css: [],
    exports: ["Avatar"],
    description: "Initials or image avatar with size, shape, and status options.",
  },
  {
    id: "skeleton",
    name: "Skeleton",
    category: "feedback",
    kind: "primitive",
    source: "skeleton.tsx",
    css: ["skeleton.css"],
    exports: ["Skeleton"],
    description: "Loading placeholder blocks, circles, and text stacks.",
  },
  {
    id: "progress",
    name: "Progress",
    category: "feedback",
    kind: "compound",
    source: "progress.tsx",
    css: ["progress.css"],
    exports: ["ProgressBar", "ProgressCircle"],
    description: "Determinate and indeterminate linear or circular progress.",
  },
  {
    id: "alert",
    name: "Alert",
    category: "feedback",
    kind: "primitive",
    source: "alert.tsx",
    css: [],
    exports: ["Alert"],
    description: "Tone-aware notice surface with optional title and dismiss control.",
  },
  {
    id: "tabs",
    name: "Tabs",
    category: "navigation",
    kind: "compound",
    source: "tabs.tsx",
    css: ["tabs.css"],
    exports: ["TabsRoot", "TabsList", "TabsTrigger", "TabsContent"],
    description: "Radix-backed tab system for switching content panels.",
  },
  {
    id: "dropdown-menu",
    name: "DropdownMenu",
    category: "overlay",
    kind: "compound",
    source: "dropdown-menu.tsx",
    css: ["menu.css"],
    exports: ["DropdownMenuRoot", "DropdownMenuTrigger", "DropdownMenuPortal", "DropdownMenuSub", "DropdownMenuSubTrigger", "DropdownMenuRadioGroup", "DropdownMenuContent", "DropdownMenuItem", "DropdownMenuSeparator", "DropdownMenuLabel", "DropdownMenuCheckboxItem", "DropdownMenuRadioItem"],
    description: "Radix-backed action menu using the shared AeroDash menu surface.",
  },
  {
    id: "select",
    name: "Select",
    category: "form",
    kind: "compound",
    source: "select.tsx",
    css: ["menu.css"],
    exports: ["SelectRoot", "SelectGroup", "SelectValue", "SelectTrigger", "SelectContent", "SelectItem", "SelectLabel", "SelectSeparator"],
    description: "Radix-backed single-select control for known option lists.",
  },
  {
    id: "toast",
    name: "Toast",
    category: "feedback",
    kind: "compound",
    source: "toast.tsx",
    css: ["toast.css"],
    exports: ["Toast", "ToastProvider", "useToast"],
    description: "In-app notification provider, hook, viewport, and toast surface.",
  },
  {
    id: "table",
    name: "Table",
    category: "data",
    kind: "compound",
    source: "table.tsx",
    css: ["table.css"],
    exports: ["TableRoot", "TableHead", "TableBody", "TableFoot", "TableRow", "TableHeader", "TableCell", "TableCaption"],
    description: "Structured data primitives with sort affordances and numeric alignment.",
  },
  {
    id: "combobox",
    name: "Combobox",
    category: "form",
    kind: "primitive",
    source: "combobox.tsx",
    css: ["menu.css"],
    exports: ["Combobox"],
    description: "Filterable single or multi-select list for free-text search flows.",
  },
  {
    id: "data-table",
    name: "DataTable",
    category: "data",
    kind: "composite",
    source: "data-table.tsx",
    css: [],
    exports: ["DataTable"],
    description: "Client-side searchable, sortable, paginated table built from table primitives.",
  },
  {
    id: "data-table-core",
    name: "DataTable Core",
    category: "data",
    kind: "utility",
    source: "data-table-core.ts",
    css: [],
    exports: ["defaultAccessor", "defaultFilter", "filterDataTableRows", "getNextDataTableSort", "paginateDataTableRows", "sortDataTableRows"],
    description: "Pure filtering, sorting, and pagination helpers used by DataTable.",
  },
  {
    id: "data-table-state",
    name: "DataTable State",
    category: "data",
    kind: "state",
    source: "data-table-state.ts",
    css: [],
    exports: ["useDataTableState"],
    description: "React hook that coordinates DataTable query, sorting, and pagination state.",
  },
  {
    id: "title-block",
    name: "TitleBlock",
    category: "shell",
    kind: "compound",
    source: "title-block.tsx",
    css: [],
    exports: ["TitleBlock", "TitleBlockRoot", "TitleBlockBody", "BoardNum", "BrandBlock", "StatusBlock"],
    description: "Landing or product header title cluster with board number and status slots.",
  },
  {
    id: "top-nav",
    name: "TopNav",
    category: "navigation",
    kind: "compound",
    source: "top-nav.tsx",
    css: [],
    exports: ["TopNavRoot", "OsTab", "TopNavTabs", "GlobalSearch", "FilterIcon"],
    description: "Chrome navigation strip for tabs, global search, and filter actions.",
  },
  {
    id: "side-rail",
    name: "SideRail",
    category: "navigation",
    kind: "compound",
    source: "side-rail.tsx",
    css: ["side-rail.css"],
    exports: ["SideRail", "RailKicker", "RailCard", "RailLogo", "RailLabel", "RailItem", "IconRail", "IconRailItem"],
    description: "Vertical navigation rail and icon grid for dense app shells.",
  },
  {
    id: "shell",
    name: "AppShell",
    category: "shell",
    kind: "compound",
    source: "shell.tsx",
    css: [],
    exports: ["AppShell", "ShellHeader", "ShellNav", "ShellRail", "AppContent", "AppFooter"],
    description: "Page shell slots for header, nav strip, rail, content, and footer.",
  },
  {
    id: "header-bar",
    name: "HeaderBar",
    category: "shell",
    kind: "compound",
    source: "header-bar.tsx",
    css: ["header-bar.css"],
    exports: ["HeaderBar", "HeaderBrand", "HeaderNav", "HeaderNavLink", "HeaderActions", "HeaderCta"],
    description: "Production-style Sedona brand header with nav and CTA zones.",
  },
  {
    id: "stats-bar",
    name: "StatsBar",
    category: "shell",
    kind: "compound",
    source: "stats-bar.tsx",
    css: ["stats-bar.css"],
    exports: ["StatsBar", "StatsSection", "StatsItem", "StatsTicker", "StatsIcons"],
    description: "Live metrics ticker strip for platform stats and market pools.",
  },
  {
    id: "chrome",
    name: "Chrome",
    category: "utility",
    kind: "utility",
    source: "chrome.tsx",
    css: [],
    exports: ["Chrome", "chromeVariants"],
    description: "Decorative SVG chrome primitive used by select visual treatments.",
  },
  {
    id: "icon-tile",
    name: "IconTile",
    category: "utility",
    kind: "primitive",
    source: "icon-tile.tsx",
    css: [],
    exports: ["IconTile", "iconTileVariants"],
    description: "Small framed icon badge for compact controls and lists.",
  },
  {
    id: "use-controllable-state",
    name: "useControllableState",
    category: "utility",
    kind: "state",
    source: "use-controllable-state.ts",
    css: [],
    exports: ["useControllableState"],
    description: "Shared controlled/uncontrolled state helper for compound inputs.",
  },
] as const satisfies readonly AerodashComponentEntry[]

export const aerodashComponentIds = aerodashComponents.map((component) => component.id)

export const aerodashCssEntryPoints = Array.from(
  new Set(aerodashComponents.flatMap((component) => component.css)),
).sort()

export const aerodashComponentCategories = Array.from(
  new Set(aerodashComponents.map((component) => component.category)),
).sort()
